sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.25.5

before_install:
  - docker-compose up --build -d

script:
  - docker-compose exec npm run test --prefix server

# local test: docker run picspiedocker_api npm run test
after_success:
  - docker build -t kaysongdocker/picspie-client ./client
  - docker build -t kaysongdocker/picspie-server ./server
  - docker build -t kaysongdocker/picspie-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kaysongdocker/picspie-client
  - docker push kaysongdocker/picspie-server
  - docker push kaysongdocker/picspie-nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ca-central-1
  app: PicsPie2
  env: Picspie2-env
  bucket_name: picspie
  bucket_path: docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
