language: generic
sudo: required

services:
  - docker

# before_install:
#   - docker build -t kaysongdocker/picspie-client -f ./client/Dockerfile.dev ./client
#   - docker build -t kaysongdocker/picspie-server -f ./server/Dockerfile.dev ./server
#   - docker build -t kaysongdocker/picspie-nginx -f ./nginx/Dockerfile.dev ./nginx

# script:
#   - docker run kaysongdocker/picspie-nginx
#   - docker run kaysongdocker/picspie-server
#   - docker run kaysongdocker/picspie-client
#   - docker run -e CI=true kaysongdocker/picspie-server npm run test

after_success:
  - docker build -t kaysongdocker/picspie-clinet ./client
  - docker build -t kaysongdocker/picspie-server ./server
  - docker build -t kaysongdocker/picspie-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kaysongdocker/picspie-clinet
  - docker push kaysongdocker/picspie-server
  - docker push kaysongdocker/picspie-nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ca-central-1
  app: PicsPie2
  env: Picspie2-env
  bucket_name: picspie
  bucket_path: docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
