version: "3"
services:
  redis:
    image: redis:latest
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3050:80
    depends_on:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - GOOGLE_CLIENT_ID=50414618384-8kuivoqh8ne3gc1bj5h2crqkf5eoador.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=y7Yx7fPFXGgx1AQ3EA3onV6-
      - MONGO_URI=mongodb+srv://kaysong:songqisyxx@cluster0-3obms.mongodb.net/PicsPie?retryWrites=true&w=majority
      - COOKIE_KEY=asndugfuwbefnaidnugbadasudhuewifiufanda
      - AWS_ACCESS_KEY=AKIAW22NRMZZODCGOE5N
      - AWS_SECRET_KEY=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
      - AWS_BUCKET=picspie
      - AWS_REGION=ca-central-1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
