version: "3"
services:
  redis:
    image: "redis:latest"
  mongo:
    image: "mongo:latest"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - client
      - api
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - GOOGLE_CLIENT_ID=50414618384-8kuivoqh8ne3gc1bj5h2crqkf5eoador.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=y7Yx7fPFXGgx1AQ3EA3onV6-
      - MONGO_URI=mongodb://mongo:27017/picspie
      - COOKIE_KEY=abcd
      - AWS_ACCESS_KEY=AKIAW22NRMZZGFH3KSIH
      - AWS_SECRET_KEY=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
      - AWS_BUCKET=picspie
      - AWS_REGION=ca-central-1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOMAIN=http://localhost:3050
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
