version: "3"
services:
  redis:
    image: "redis:latest"
  mongo:
    image: "mongo:latest"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - client
      - api
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - MONGO_URI=
      - COOKIE_KEY=
      - AWS_ACCESS_KEY=
      - AWS_SECRET_KEY=
      - AWS_BUCKET=
      - AWS_REGION=
      - REDIS_HOST=
      - REDIS_PORT=
      - DOMAIN=
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
